-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity orGate is
port (
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC;
    b : IN STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of orGate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal or_ln17_fu_18_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln17_fu_18_p1 : STD_LOGIC_VECTOR (0 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= (or_ln17_fu_18_p1 or or_ln17_fu_18_p0);
    or_ln17_fu_18_p0 <= (0=>a, others=>'-');
    or_ln17_fu_18_p1 <= (0=>b, others=>'-');
end behav;
