// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inOutFunction,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=30.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=22.344000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=9,HLS_SYN_FF=0,HLS_SYN_LUT=180,HLS_VERSION=2020_1}" *)

module inOutFunction (
        a,
        b,
        c,
        f
);


input  [31:0] a;
input  [31:0] b;
input  [31:0] c;
output  [31:0] f;

wire  signed [31:0] add_ln12_fu_53_p0;
wire  signed [31:0] add_ln12_fu_53_p1;
wire  signed [31:0] add_ln12_fu_53_p2;
wire  signed [31:0] mul_ln12_fu_59_p1;
wire  signed [31:0] mul_ln12_1_fu_65_p0;
wire  signed [31:0] mul_ln12_1_fu_65_p1;
wire   [31:0] mul_ln12_1_fu_65_p2;
wire  signed [31:0] tmp_fu_71_p1;
wire  signed [31:0] tmp_fu_71_p2;
wire  signed [31:0] tmp1_fu_77_p1;
wire   [31:0] tmp1_fu_77_p2;
wire   [31:0] mul_ln12_fu_59_p2;

assign add_ln12_fu_53_p0 = c;

assign add_ln12_fu_53_p1 = b;

assign add_ln12_fu_53_p2 = ($signed(add_ln12_fu_53_p0) + $signed(add_ln12_fu_53_p1));

assign f = (tmp1_fu_77_p2 + mul_ln12_fu_59_p2);

assign mul_ln12_1_fu_65_p0 = b;

assign mul_ln12_1_fu_65_p1 = a;

assign mul_ln12_1_fu_65_p2 = ($signed(mul_ln12_1_fu_65_p0) * $signed(mul_ln12_1_fu_65_p1));

assign mul_ln12_fu_59_p1 = a;

assign mul_ln12_fu_59_p2 = ($signed(add_ln12_fu_53_p2) * $signed(mul_ln12_fu_59_p1));

assign tmp1_fu_77_p1 = c;

assign tmp1_fu_77_p2 = ($signed(tmp_fu_71_p2) * $signed(tmp1_fu_77_p1));

assign tmp_fu_71_p1 = b;

assign tmp_fu_71_p2 = ($signed(mul_ln12_1_fu_65_p2) + $signed(tmp_fu_71_p1));

endmodule //inOutFunction
