// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inOutFunction,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=20.963000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=13,HLS_SYN_FF=0,HLS_SYN_LUT=123,HLS_VERSION=2020_1}" *)

module inOutFunction (
        a,
        b,
        c,
        d,
        f
);


input  [31:0] a;
input  [31:0] b;
input  [31:0] c;
input  [31:0] d;
output  [31:0] f;

wire   [31:0] t_4_fu_101_p2;
wire  signed [31:0] t_fu_71_p0;
wire  signed [31:0] t_fu_71_p1;
wire  signed [31:0] t_1_fu_77_p0;
wire  signed [31:0] t_1_fu_77_p1;
wire  signed [31:0] t_1_fu_77_p2;
wire  signed [31:0] t_fu_71_p2;
wire  signed [31:0] add_ln15_fu_89_p0;
wire  signed [31:0] add_ln15_fu_89_p1;
wire  signed [31:0] add_ln15_fu_89_p2;
wire  signed [31:0] t_3_fu_95_p1;
wire   [31:0] t_4_fu_101_p0;
wire   [31:0] t_4_fu_101_p1;

inOutFunction_addbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
inOutFunction_addbkb_U1(
    .din0(t_4_fu_101_p0),
    .din1(t_4_fu_101_p1),
    .dout(t_4_fu_101_p2)
);

assign add_ln15_fu_89_p0 = c;

assign add_ln15_fu_89_p1 = b;

assign add_ln15_fu_89_p2 = ($signed(add_ln15_fu_89_p0) + $signed(add_ln15_fu_89_p1));

assign f = t_4_fu_101_p2;

assign t_1_fu_77_p0 = d;

assign t_1_fu_77_p1 = c;

assign t_1_fu_77_p2 = ($signed(t_1_fu_77_p0) * $signed(t_1_fu_77_p1));

assign t_3_fu_95_p1 = a;

assign t_4_fu_101_p0 = ($signed(t_1_fu_77_p2) * $signed(t_fu_71_p2));

assign t_4_fu_101_p1 = ($signed(add_ln15_fu_89_p2) * $signed(t_3_fu_95_p1));

assign t_fu_71_p0 = b;

assign t_fu_71_p1 = a;

assign t_fu_71_p2 = ($signed(t_fu_71_p0) * $signed(t_fu_71_p1));

endmodule //inOutFunction
