// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module andGate (
        ap_ready,
        a,
        b,
        ap_return
);


output   ap_ready;
input   a;
input   b;
output  [0:0] ap_return;

wire   [0:0] and_ln5_fu_18_p0;
wire   [0:0] and_ln5_fu_18_p1;

assign and_ln5_fu_18_p0 = a;

assign and_ln5_fu_18_p1 = b;

assign ap_ready = 1'b1;

assign ap_return = (and_ln5_fu_18_p1 & and_ln5_fu_18_p0);

endmodule //andGate
