// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inout_inlineoff,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.956000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=6,HLS_VERSION=2020_1}" *)

module inout_inlineoff (
        a,
        b,
        c,
        d
);


input   a;
input   b;
input   c;
output   d;

wire    tmp_andGate_fu_59_ap_ready;
wire   [0:0] tmp_andGate_fu_59_ap_return;
wire    tmp_2_orGate_fu_67_ap_ready;
wire    tmp_2_orGate_fu_67_a;
wire    tmp_2_orGate_fu_67_b;
wire   [0:0] tmp_2_orGate_fu_67_ap_return;
wire    tmp_1_notGate_fu_75_ap_ready;
wire   [0:0] tmp_1_notGate_fu_75_ap_return;

andGate tmp_andGate_fu_59(
    .ap_ready(tmp_andGate_fu_59_ap_ready),
    .a(a),
    .b(b),
    .ap_return(tmp_andGate_fu_59_ap_return)
);

orGate tmp_2_orGate_fu_67(
    .ap_ready(tmp_2_orGate_fu_67_ap_ready),
    .a(tmp_2_orGate_fu_67_a),
    .b(tmp_2_orGate_fu_67_b),
    .ap_return(tmp_2_orGate_fu_67_ap_return)
);

notGate tmp_1_notGate_fu_75(
    .ap_ready(tmp_1_notGate_fu_75_ap_ready),
    .a(c),
    .ap_return(tmp_1_notGate_fu_75_ap_return)
);

assign d = tmp_2_orGate_fu_67_ap_return;

assign tmp_2_orGate_fu_67_a = tmp_andGate_fu_59_ap_return;

assign tmp_2_orGate_fu_67_b = tmp_1_notGate_fu_75_ap_return;

endmodule //inout_inlineoff
