// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _inOutFunction_HH_
#define _inOutFunction_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct inOutFunction : public sc_module {
    // Port declarations 4
    sc_in< sc_lv<32> > a;
    sc_in< sc_lv<32> > b;
    sc_in< sc_lv<32> > c;
    sc_out< sc_lv<32> > f;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    inOutFunction(sc_module_name name);
    SC_HAS_PROCESS(inOutFunction);

    ~inOutFunction();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<32> > add_ln12_fu_53_p0;
    sc_signal< sc_lv<32> > add_ln12_fu_53_p1;
    sc_signal< sc_lv<32> > add_ln12_fu_53_p2;
    sc_signal< sc_lv<32> > mul_ln12_fu_59_p1;
    sc_signal< sc_lv<32> > mul_ln12_1_fu_65_p0;
    sc_signal< sc_lv<32> > mul_ln12_1_fu_65_p1;
    sc_signal< sc_lv<32> > mul_ln12_1_fu_65_p2;
    sc_signal< sc_lv<32> > tmp_fu_71_p1;
    sc_signal< sc_lv<32> > tmp_fu_71_p2;
    sc_signal< sc_lv<32> > tmp1_fu_77_p1;
    sc_signal< sc_lv<32> > tmp1_fu_77_p2;
    sc_signal< sc_lv<32> > mul_ln12_fu_59_p2;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_add_ln12_fu_53_p0();
    void thread_add_ln12_fu_53_p1();
    void thread_add_ln12_fu_53_p2();
    void thread_f();
    void thread_mul_ln12_1_fu_65_p0();
    void thread_mul_ln12_1_fu_65_p1();
    void thread_mul_ln12_1_fu_65_p2();
    void thread_mul_ln12_fu_59_p1();
    void thread_mul_ln12_fu_59_p2();
    void thread_tmp1_fu_77_p1();
    void thread_tmp1_fu_77_p2();
    void thread_tmp_fu_71_p1();
    void thread_tmp_fu_71_p2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
