// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _inOutFunction_HH_
#define _inOutFunction_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "inOutFunction_sevbkb.h"

namespace ap_rtl {

struct inOutFunction : public sc_module {
    // Port declarations 6
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > inNumber_V;
    sc_in< sc_lv<4> > pushButton_V;
    sc_out< sc_lv<4> > anodes_V;
    sc_out< sc_lv<8> > outputSegments_V;


    // Module declarations
    inOutFunction(sc_module_name name);
    SC_HAS_PROCESS(inOutFunction);

    ~inOutFunction();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    inOutFunction_sevbkb* sevenSegmentNumbers_U;
    sc_signal< sc_lv<4> > sevenSegmentNumbers_address0;
    sc_signal< sc_logic > sevenSegmentNumbers_ce0;
    sc_signal< sc_lv<7> > sevenSegmentNumbers_q0;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<36> > dabble_V_fu_234_p1;
    sc_signal< sc_lv<5> > e_fu_244_p2;
    sc_signal< sc_lv<5> > e_reg_583;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > trunc_ln791_fu_250_p1;
    sc_signal< sc_lv<1> > trunc_ln791_reg_588;
    sc_signal< sc_lv<1> > icmp_ln15_fu_238_p2;
    sc_signal< sc_lv<1> > tmp_fu_253_p3;
    sc_signal< sc_lv<1> > tmp_reg_592;
    sc_signal< sc_lv<1> > tmp_1_fu_260_p3;
    sc_signal< sc_lv<1> > tmp_1_reg_596;
    sc_signal< sc_lv<1> > tmp_5_fu_267_p3;
    sc_signal< sc_lv<1> > tmp_5_reg_600;
    sc_signal< sc_lv<3> > i_fu_340_p2;
    sc_signal< sc_lv<3> > i_reg_627;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<6> > zext_ln19_fu_354_p1;
    sc_signal< sc_lv<6> > zext_ln19_reg_632;
    sc_signal< sc_lv<1> > icmp_ln17_fu_334_p2;
    sc_signal< sc_lv<6> > add_ln19_fu_359_p2;
    sc_signal< sc_lv<6> > add_ln19_reg_637;
    sc_signal< sc_lv<6> > add_ln19_1_fu_366_p2;
    sc_signal< sc_lv<6> > add_ln19_1_reg_644;
    sc_signal< sc_lv<4> > trunc_ln647_fu_409_p1;
    sc_signal< sc_lv<4> > trunc_ln647_reg_652;
    sc_signal< sc_lv<36> > r_V_fu_413_p2;
    sc_signal< sc_lv<1> > icmp_ln895_fu_426_p2;
    sc_signal< sc_lv<1> > icmp_ln895_reg_662;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<36> > p_Result_8_fu_535_p2;
    sc_signal< sc_lv<36> > p_Result_8_reg_667;
    sc_signal< sc_lv<36> > dabble_V_3_fu_541_p3;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<36> > p_Val2_s_reg_182;
    sc_signal< sc_lv<5> > e_0_i_reg_192;
    sc_signal< sc_lv<36> > p_Val2_1_reg_203;
    sc_signal< sc_lv<3> > i_0_i_reg_214;
    sc_signal< sc_lv<64> > zext_ln681_3_fu_284_p1;
    sc_signal< sc_lv<64> > zext_ln681_2_fu_299_p1;
    sc_signal< sc_lv<64> > zext_ln681_1_fu_314_p1;
    sc_signal< sc_lv<64> > zext_ln681_fu_329_p1;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<8> > zext_ln59_fu_547_p1;
    sc_signal< sc_lv<8> > zext_ln54_fu_552_p1;
    sc_signal< sc_lv<8> > zext_ln48_fu_557_p1;
    sc_signal< sc_lv<8> > zext_ln43_fu_562_p1;
    sc_signal< sc_lv<6> > grp_fu_225_p0;
    sc_signal< sc_lv<6> > grp_fu_225_p1;
    sc_signal< sc_lv<6> > grp_fu_229_p1;
    sc_signal< sc_lv<4> > p_Result_3_fu_274_p4;
    sc_signal< sc_lv<4> > p_Result_2_fu_289_p4;
    sc_signal< sc_lv<4> > p_Result_1_fu_304_p4;
    sc_signal< sc_lv<4> > p_Result_s_fu_319_p4;
    sc_signal< sc_lv<5> > shl_ln_fu_346_p3;
    sc_signal< sc_lv<1> > grp_fu_225_p2;
    sc_signal< sc_lv<36> > tmp_2_fu_373_p4;
    sc_signal< sc_lv<6> > grp_fu_229_p2;
    sc_signal< sc_lv<6> > select_ln647_1_fu_391_p3;
    sc_signal< sc_lv<36> > select_ln647_fu_383_p3;
    sc_signal< sc_lv<36> > zext_ln647_fu_399_p1;
    sc_signal< sc_lv<36> > lshr_ln647_fu_403_p2;
    sc_signal< sc_lv<36> > p_Result_7_fu_419_p3;
    sc_signal< sc_lv<6> > select_ln414_fu_438_p3;
    sc_signal< sc_lv<6> > select_ln414_2_fu_450_p3;
    sc_signal< sc_lv<6> > select_ln414_1_fu_444_p3;
    sc_signal< sc_lv<6> > sub_ln414_1_fu_457_p2;
    sc_signal< sc_lv<36> > tmp_V_fu_432_p2;
    sc_signal< sc_lv<36> > zext_ln414_fu_463_p1;
    sc_signal< sc_lv<36> > shl_ln414_fu_475_p2;
    sc_signal< sc_lv<36> > tmp_4_fu_481_p4;
    sc_signal< sc_lv<36> > zext_ln414_1_fu_467_p1;
    sc_signal< sc_lv<36> > zext_ln414_2_fu_471_p1;
    sc_signal< sc_lv<36> > shl_ln414_1_fu_499_p2;
    sc_signal< sc_lv<36> > lshr_ln414_fu_505_p2;
    sc_signal< sc_lv<36> > and_ln414_fu_511_p2;
    sc_signal< sc_lv<36> > xor_ln414_fu_517_p2;
    sc_signal< sc_lv<36> > select_ln414_3_fu_491_p3;
    sc_signal< sc_lv<36> > and_ln414_1_fu_523_p2;
    sc_signal< sc_lv<36> > and_ln414_2_fu_529_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< bool > ap_condition_155;
    sc_signal< bool > ap_condition_159;
    sc_signal< bool > ap_condition_414;
    sc_signal< bool > ap_condition_417;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<6> ap_const_lv6_13;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<6> ap_const_lv6_10;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<36> ap_const_lv36_1;
    static const sc_lv<36> ap_const_lv36_4;
    static const sc_lv<36> ap_const_lv36_3;
    static const sc_lv<6> ap_const_lv6_23;
    static const sc_lv<36> ap_const_lv36_FFFFFFFFF;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln19_1_fu_366_p2();
    void thread_add_ln19_fu_359_p2();
    void thread_and_ln414_1_fu_523_p2();
    void thread_and_ln414_2_fu_529_p2();
    void thread_and_ln414_fu_511_p2();
    void thread_anodes_V();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_condition_155();
    void thread_ap_condition_159();
    void thread_ap_condition_414();
    void thread_ap_condition_417();
    void thread_dabble_V_3_fu_541_p3();
    void thread_dabble_V_fu_234_p1();
    void thread_e_fu_244_p2();
    void thread_grp_fu_225_p0();
    void thread_grp_fu_225_p1();
    void thread_grp_fu_225_p2();
    void thread_grp_fu_229_p1();
    void thread_grp_fu_229_p2();
    void thread_i_fu_340_p2();
    void thread_icmp_ln15_fu_238_p2();
    void thread_icmp_ln17_fu_334_p2();
    void thread_icmp_ln895_fu_426_p2();
    void thread_lshr_ln414_fu_505_p2();
    void thread_lshr_ln647_fu_403_p2();
    void thread_outputSegments_V();
    void thread_p_Result_1_fu_304_p4();
    void thread_p_Result_2_fu_289_p4();
    void thread_p_Result_3_fu_274_p4();
    void thread_p_Result_7_fu_419_p3();
    void thread_p_Result_8_fu_535_p2();
    void thread_p_Result_s_fu_319_p4();
    void thread_r_V_fu_413_p2();
    void thread_select_ln414_1_fu_444_p3();
    void thread_select_ln414_2_fu_450_p3();
    void thread_select_ln414_3_fu_491_p3();
    void thread_select_ln414_fu_438_p3();
    void thread_select_ln647_1_fu_391_p3();
    void thread_select_ln647_fu_383_p3();
    void thread_sevenSegmentNumbers_address0();
    void thread_sevenSegmentNumbers_ce0();
    void thread_shl_ln414_1_fu_499_p2();
    void thread_shl_ln414_fu_475_p2();
    void thread_shl_ln_fu_346_p3();
    void thread_sub_ln414_1_fu_457_p2();
    void thread_tmp_1_fu_260_p3();
    void thread_tmp_2_fu_373_p4();
    void thread_tmp_4_fu_481_p4();
    void thread_tmp_5_fu_267_p3();
    void thread_tmp_V_fu_432_p2();
    void thread_tmp_fu_253_p3();
    void thread_trunc_ln647_fu_409_p1();
    void thread_trunc_ln791_fu_250_p1();
    void thread_xor_ln414_fu_517_p2();
    void thread_zext_ln19_fu_354_p1();
    void thread_zext_ln414_1_fu_467_p1();
    void thread_zext_ln414_2_fu_471_p1();
    void thread_zext_ln414_fu_463_p1();
    void thread_zext_ln43_fu_562_p1();
    void thread_zext_ln48_fu_557_p1();
    void thread_zext_ln54_fu_552_p1();
    void thread_zext_ln59_fu_547_p1();
    void thread_zext_ln647_fu_399_p1();
    void thread_zext_ln681_1_fu_314_p1();
    void thread_zext_ln681_2_fu_299_p1();
    void thread_zext_ln681_3_fu_284_p1();
    void thread_zext_ln681_fu_329_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
