// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "inOutFunction.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic inOutFunction::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic inOutFunction::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> inOutFunction::ap_ST_fsm_state1 = "1";
const sc_lv<6> inOutFunction::ap_ST_fsm_state2 = "10";
const sc_lv<6> inOutFunction::ap_ST_fsm_state3 = "100";
const sc_lv<6> inOutFunction::ap_ST_fsm_state4 = "1000";
const sc_lv<6> inOutFunction::ap_ST_fsm_state5 = "10000";
const sc_lv<6> inOutFunction::ap_ST_fsm_state6 = "100000";
const sc_lv<32> inOutFunction::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> inOutFunction::ap_const_lv32_1 = "1";
const sc_lv<1> inOutFunction::ap_const_lv1_1 = "1";
const sc_lv<1> inOutFunction::ap_const_lv1_0 = "0";
const sc_lv<32> inOutFunction::ap_const_lv32_2 = "10";
const sc_lv<32> inOutFunction::ap_const_lv32_3 = "11";
const sc_lv<32> inOutFunction::ap_const_lv32_4 = "100";
const sc_lv<5> inOutFunction::ap_const_lv5_0 = "00000";
const sc_lv<3> inOutFunction::ap_const_lv3_0 = "000";
const sc_lv<4> inOutFunction::ap_const_lv4_F = "1111";
const sc_lv<4> inOutFunction::ap_const_lv4_7 = "111";
const sc_lv<32> inOutFunction::ap_const_lv32_5 = "101";
const sc_lv<4> inOutFunction::ap_const_lv4_B = "1011";
const sc_lv<4> inOutFunction::ap_const_lv4_D = "1101";
const sc_lv<4> inOutFunction::ap_const_lv4_E = "1110";
const sc_lv<6> inOutFunction::ap_const_lv6_13 = "10011";
const sc_lv<5> inOutFunction::ap_const_lv5_10 = "10000";
const sc_lv<5> inOutFunction::ap_const_lv5_1 = "1";
const sc_lv<32> inOutFunction::ap_const_lv32_1C = "11100";
const sc_lv<32> inOutFunction::ap_const_lv32_1F = "11111";
const sc_lv<32> inOutFunction::ap_const_lv32_18 = "11000";
const sc_lv<32> inOutFunction::ap_const_lv32_1B = "11011";
const sc_lv<32> inOutFunction::ap_const_lv32_14 = "10100";
const sc_lv<32> inOutFunction::ap_const_lv32_17 = "10111";
const sc_lv<32> inOutFunction::ap_const_lv32_10 = "10000";
const sc_lv<32> inOutFunction::ap_const_lv32_13 = "10011";
const sc_lv<3> inOutFunction::ap_const_lv3_5 = "101";
const sc_lv<3> inOutFunction::ap_const_lv3_1 = "1";
const sc_lv<2> inOutFunction::ap_const_lv2_0 = "00";
const sc_lv<6> inOutFunction::ap_const_lv6_10 = "10000";
const sc_lv<32> inOutFunction::ap_const_lv32_23 = "100011";
const sc_lv<36> inOutFunction::ap_const_lv36_1 = "1";
const sc_lv<36> inOutFunction::ap_const_lv36_4 = "100";
const sc_lv<36> inOutFunction::ap_const_lv36_3 = "11";
const sc_lv<6> inOutFunction::ap_const_lv6_23 = "100011";
const sc_lv<36> inOutFunction::ap_const_lv36_FFFFFFFFF = "111111111111111111111111111111111111";
const bool inOutFunction::ap_const_boolean_1 = true;

inOutFunction::inOutFunction(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sevenSegmentNumbers_U = new inOutFunction_sevbkb("sevenSegmentNumbers_U");
    sevenSegmentNumbers_U->clk(ap_clk);
    sevenSegmentNumbers_U->reset(ap_rst);
    sevenSegmentNumbers_U->address0(sevenSegmentNumbers_address0);
    sevenSegmentNumbers_U->ce0(sevenSegmentNumbers_ce0);
    sevenSegmentNumbers_U->q0(sevenSegmentNumbers_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln19_1_fu_366_p2);
    sensitive << ( zext_ln19_fu_354_p1 );

    SC_METHOD(thread_add_ln19_fu_359_p2);
    sensitive << ( zext_ln19_fu_354_p1 );

    SC_METHOD(thread_and_ln414_1_fu_523_p2);
    sensitive << ( p_Val2_1_reg_203 );
    sensitive << ( xor_ln414_fu_517_p2 );

    SC_METHOD(thread_and_ln414_2_fu_529_p2);
    sensitive << ( and_ln414_fu_511_p2 );
    sensitive << ( select_ln414_3_fu_491_p3 );

    SC_METHOD(thread_and_ln414_fu_511_p2);
    sensitive << ( shl_ln414_1_fu_499_p2 );
    sensitive << ( lshr_ln414_fu_505_p2 );

    SC_METHOD(thread_anodes_V);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( trunc_ln791_fu_250_p1 );
    sensitive << ( trunc_ln791_reg_588 );
    sensitive << ( icmp_ln15_fu_238_p2 );
    sensitive << ( tmp_fu_253_p3 );
    sensitive << ( tmp_reg_592 );
    sensitive << ( tmp_1_fu_260_p3 );
    sensitive << ( tmp_1_reg_596 );
    sensitive << ( tmp_5_fu_267_p3 );
    sensitive << ( tmp_5_reg_600 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_155);
    sensitive << ( trunc_ln791_reg_588 );
    sensitive << ( tmp_reg_592 );
    sensitive << ( tmp_1_reg_596 );
    sensitive << ( tmp_5_reg_600 );

    SC_METHOD(thread_ap_condition_159);
    sensitive << ( trunc_ln791_reg_588 );
    sensitive << ( tmp_reg_592 );
    sensitive << ( tmp_1_reg_596 );

    SC_METHOD(thread_ap_condition_414);
    sensitive << ( trunc_ln791_fu_250_p1 );
    sensitive << ( tmp_fu_253_p3 );
    sensitive << ( tmp_1_fu_260_p3 );
    sensitive << ( tmp_5_fu_267_p3 );

    SC_METHOD(thread_ap_condition_417);
    sensitive << ( trunc_ln791_fu_250_p1 );
    sensitive << ( tmp_fu_253_p3 );
    sensitive << ( tmp_1_fu_260_p3 );

    SC_METHOD(thread_dabble_V_3_fu_541_p3);
    sensitive << ( icmp_ln895_reg_662 );
    sensitive << ( p_Result_8_reg_667 );
    sensitive << ( p_Val2_1_reg_203 );

    SC_METHOD(thread_dabble_V_fu_234_p1);
    sensitive << ( inNumber_V );

    SC_METHOD(thread_e_fu_244_p2);
    sensitive << ( e_0_i_reg_192 );

    SC_METHOD(thread_grp_fu_225_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( add_ln19_1_fu_366_p2 );
    sensitive << ( add_ln19_1_reg_644 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_225_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( add_ln19_fu_359_p2 );
    sensitive << ( add_ln19_reg_637 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_225_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln17_fu_334_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_fu_225_p0 );
    sensitive << ( grp_fu_225_p1 );

    SC_METHOD(thread_grp_fu_229_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln19_fu_354_p1 );
    sensitive << ( zext_ln19_reg_632 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_229_p2);
    sensitive << ( grp_fu_229_p1 );

    SC_METHOD(thread_i_fu_340_p2);
    sensitive << ( i_0_i_reg_214 );

    SC_METHOD(thread_icmp_ln15_fu_238_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( e_0_i_reg_192 );

    SC_METHOD(thread_icmp_ln17_fu_334_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_i_reg_214 );

    SC_METHOD(thread_icmp_ln895_fu_426_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_Result_7_fu_419_p3 );

    SC_METHOD(thread_lshr_ln414_fu_505_p2);
    sensitive << ( zext_ln414_2_fu_471_p1 );

    SC_METHOD(thread_lshr_ln647_fu_403_p2);
    sensitive << ( select_ln647_fu_383_p3 );
    sensitive << ( zext_ln647_fu_399_p1 );

    SC_METHOD(thread_outputSegments_V);
    sensitive << ( trunc_ln791_reg_588 );
    sensitive << ( tmp_reg_592 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln59_fu_547_p1 );
    sensitive << ( zext_ln54_fu_552_p1 );
    sensitive << ( zext_ln48_fu_557_p1 );
    sensitive << ( zext_ln43_fu_562_p1 );
    sensitive << ( ap_condition_155 );
    sensitive << ( ap_condition_159 );

    SC_METHOD(thread_p_Result_1_fu_304_p4);
    sensitive << ( p_Val2_s_reg_182 );

    SC_METHOD(thread_p_Result_2_fu_289_p4);
    sensitive << ( p_Val2_s_reg_182 );

    SC_METHOD(thread_p_Result_3_fu_274_p4);
    sensitive << ( p_Val2_s_reg_182 );

    SC_METHOD(thread_p_Result_7_fu_419_p3);
    sensitive << ( trunc_ln647_reg_652 );

    SC_METHOD(thread_p_Result_8_fu_535_p2);
    sensitive << ( and_ln414_1_fu_523_p2 );
    sensitive << ( and_ln414_2_fu_529_p2 );

    SC_METHOD(thread_p_Result_s_fu_319_p4);
    sensitive << ( p_Val2_s_reg_182 );

    SC_METHOD(thread_r_V_fu_413_p2);
    sensitive << ( p_Val2_1_reg_203 );

    SC_METHOD(thread_select_ln414_1_fu_444_p3);
    sensitive << ( add_ln19_reg_637 );
    sensitive << ( add_ln19_1_reg_644 );
    sensitive << ( grp_fu_225_p2 );

    SC_METHOD(thread_select_ln414_2_fu_450_p3);
    sensitive << ( add_ln19_1_reg_644 );
    sensitive << ( grp_fu_225_p2 );
    sensitive << ( grp_fu_229_p2 );

    SC_METHOD(thread_select_ln414_3_fu_491_p3);
    sensitive << ( grp_fu_225_p2 );
    sensitive << ( shl_ln414_fu_475_p2 );
    sensitive << ( tmp_4_fu_481_p4 );

    SC_METHOD(thread_select_ln414_fu_438_p3);
    sensitive << ( add_ln19_reg_637 );
    sensitive << ( add_ln19_1_reg_644 );
    sensitive << ( grp_fu_225_p2 );

    SC_METHOD(thread_select_ln647_1_fu_391_p3);
    sensitive << ( add_ln19_1_fu_366_p2 );
    sensitive << ( grp_fu_225_p2 );
    sensitive << ( grp_fu_229_p2 );

    SC_METHOD(thread_select_ln647_fu_383_p3);
    sensitive << ( p_Val2_1_reg_203 );
    sensitive << ( grp_fu_225_p2 );
    sensitive << ( tmp_2_fu_373_p4 );

    SC_METHOD(thread_sevenSegmentNumbers_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( trunc_ln791_fu_250_p1 );
    sensitive << ( icmp_ln15_fu_238_p2 );
    sensitive << ( tmp_fu_253_p3 );
    sensitive << ( zext_ln681_3_fu_284_p1 );
    sensitive << ( zext_ln681_2_fu_299_p1 );
    sensitive << ( zext_ln681_1_fu_314_p1 );
    sensitive << ( zext_ln681_fu_329_p1 );
    sensitive << ( ap_condition_414 );
    sensitive << ( ap_condition_417 );

    SC_METHOD(thread_sevenSegmentNumbers_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( trunc_ln791_fu_250_p1 );
    sensitive << ( icmp_ln15_fu_238_p2 );
    sensitive << ( tmp_fu_253_p3 );
    sensitive << ( tmp_1_fu_260_p3 );
    sensitive << ( tmp_5_fu_267_p3 );

    SC_METHOD(thread_shl_ln414_1_fu_499_p2);
    sensitive << ( zext_ln414_1_fu_467_p1 );

    SC_METHOD(thread_shl_ln414_fu_475_p2);
    sensitive << ( tmp_V_fu_432_p2 );
    sensitive << ( zext_ln414_fu_463_p1 );

    SC_METHOD(thread_shl_ln_fu_346_p3);
    sensitive << ( i_0_i_reg_214 );

    SC_METHOD(thread_sub_ln414_1_fu_457_p2);
    sensitive << ( select_ln414_fu_438_p3 );

    SC_METHOD(thread_tmp_1_fu_260_p3);
    sensitive << ( pushButton_V );

    SC_METHOD(thread_tmp_2_fu_373_p4);
    sensitive << ( p_Val2_1_reg_203 );

    SC_METHOD(thread_tmp_4_fu_481_p4);
    sensitive << ( shl_ln414_fu_475_p2 );

    SC_METHOD(thread_tmp_5_fu_267_p3);
    sensitive << ( pushButton_V );

    SC_METHOD(thread_tmp_V_fu_432_p2);
    sensitive << ( p_Result_7_fu_419_p3 );

    SC_METHOD(thread_tmp_fu_253_p3);
    sensitive << ( pushButton_V );

    SC_METHOD(thread_trunc_ln647_fu_409_p1);
    sensitive << ( lshr_ln647_fu_403_p2 );

    SC_METHOD(thread_trunc_ln791_fu_250_p1);
    sensitive << ( pushButton_V );

    SC_METHOD(thread_xor_ln414_fu_517_p2);
    sensitive << ( and_ln414_fu_511_p2 );

    SC_METHOD(thread_zext_ln19_fu_354_p1);
    sensitive << ( shl_ln_fu_346_p3 );

    SC_METHOD(thread_zext_ln414_1_fu_467_p1);
    sensitive << ( select_ln414_1_fu_444_p3 );

    SC_METHOD(thread_zext_ln414_2_fu_471_p1);
    sensitive << ( sub_ln414_1_fu_457_p2 );

    SC_METHOD(thread_zext_ln414_fu_463_p1);
    sensitive << ( select_ln414_2_fu_450_p3 );

    SC_METHOD(thread_zext_ln43_fu_562_p1);
    sensitive << ( sevenSegmentNumbers_q0 );

    SC_METHOD(thread_zext_ln48_fu_557_p1);
    sensitive << ( sevenSegmentNumbers_q0 );

    SC_METHOD(thread_zext_ln54_fu_552_p1);
    sensitive << ( sevenSegmentNumbers_q0 );

    SC_METHOD(thread_zext_ln59_fu_547_p1);
    sensitive << ( sevenSegmentNumbers_q0 );

    SC_METHOD(thread_zext_ln647_fu_399_p1);
    sensitive << ( select_ln647_1_fu_391_p3 );

    SC_METHOD(thread_zext_ln681_1_fu_314_p1);
    sensitive << ( p_Result_1_fu_304_p4 );

    SC_METHOD(thread_zext_ln681_2_fu_299_p1);
    sensitive << ( p_Result_2_fu_289_p4 );

    SC_METHOD(thread_zext_ln681_3_fu_284_p1);
    sensitive << ( p_Result_3_fu_274_p4 );

    SC_METHOD(thread_zext_ln681_fu_329_p1);
    sensitive << ( p_Result_s_fu_319_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln15_fu_238_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln17_fu_334_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "inOutFunction_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, inNumber_V, "(port)inNumber_V");
    sc_trace(mVcdFile, pushButton_V, "(port)pushButton_V");
    sc_trace(mVcdFile, anodes_V, "(port)anodes_V");
    sc_trace(mVcdFile, outputSegments_V, "(port)outputSegments_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, sevenSegmentNumbers_address0, "sevenSegmentNumbers_address0");
    sc_trace(mVcdFile, sevenSegmentNumbers_ce0, "sevenSegmentNumbers_ce0");
    sc_trace(mVcdFile, sevenSegmentNumbers_q0, "sevenSegmentNumbers_q0");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dabble_V_fu_234_p1, "dabble_V_fu_234_p1");
    sc_trace(mVcdFile, e_fu_244_p2, "e_fu_244_p2");
    sc_trace(mVcdFile, e_reg_583, "e_reg_583");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, trunc_ln791_fu_250_p1, "trunc_ln791_fu_250_p1");
    sc_trace(mVcdFile, trunc_ln791_reg_588, "trunc_ln791_reg_588");
    sc_trace(mVcdFile, icmp_ln15_fu_238_p2, "icmp_ln15_fu_238_p2");
    sc_trace(mVcdFile, tmp_fu_253_p3, "tmp_fu_253_p3");
    sc_trace(mVcdFile, tmp_reg_592, "tmp_reg_592");
    sc_trace(mVcdFile, tmp_1_fu_260_p3, "tmp_1_fu_260_p3");
    sc_trace(mVcdFile, tmp_1_reg_596, "tmp_1_reg_596");
    sc_trace(mVcdFile, tmp_5_fu_267_p3, "tmp_5_fu_267_p3");
    sc_trace(mVcdFile, tmp_5_reg_600, "tmp_5_reg_600");
    sc_trace(mVcdFile, i_fu_340_p2, "i_fu_340_p2");
    sc_trace(mVcdFile, i_reg_627, "i_reg_627");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln19_fu_354_p1, "zext_ln19_fu_354_p1");
    sc_trace(mVcdFile, zext_ln19_reg_632, "zext_ln19_reg_632");
    sc_trace(mVcdFile, icmp_ln17_fu_334_p2, "icmp_ln17_fu_334_p2");
    sc_trace(mVcdFile, add_ln19_fu_359_p2, "add_ln19_fu_359_p2");
    sc_trace(mVcdFile, add_ln19_reg_637, "add_ln19_reg_637");
    sc_trace(mVcdFile, add_ln19_1_fu_366_p2, "add_ln19_1_fu_366_p2");
    sc_trace(mVcdFile, add_ln19_1_reg_644, "add_ln19_1_reg_644");
    sc_trace(mVcdFile, trunc_ln647_fu_409_p1, "trunc_ln647_fu_409_p1");
    sc_trace(mVcdFile, trunc_ln647_reg_652, "trunc_ln647_reg_652");
    sc_trace(mVcdFile, r_V_fu_413_p2, "r_V_fu_413_p2");
    sc_trace(mVcdFile, icmp_ln895_fu_426_p2, "icmp_ln895_fu_426_p2");
    sc_trace(mVcdFile, icmp_ln895_reg_662, "icmp_ln895_reg_662");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, p_Result_8_fu_535_p2, "p_Result_8_fu_535_p2");
    sc_trace(mVcdFile, p_Result_8_reg_667, "p_Result_8_reg_667");
    sc_trace(mVcdFile, dabble_V_3_fu_541_p3, "dabble_V_3_fu_541_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, p_Val2_s_reg_182, "p_Val2_s_reg_182");
    sc_trace(mVcdFile, e_0_i_reg_192, "e_0_i_reg_192");
    sc_trace(mVcdFile, p_Val2_1_reg_203, "p_Val2_1_reg_203");
    sc_trace(mVcdFile, i_0_i_reg_214, "i_0_i_reg_214");
    sc_trace(mVcdFile, zext_ln681_3_fu_284_p1, "zext_ln681_3_fu_284_p1");
    sc_trace(mVcdFile, zext_ln681_2_fu_299_p1, "zext_ln681_2_fu_299_p1");
    sc_trace(mVcdFile, zext_ln681_1_fu_314_p1, "zext_ln681_1_fu_314_p1");
    sc_trace(mVcdFile, zext_ln681_fu_329_p1, "zext_ln681_fu_329_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln59_fu_547_p1, "zext_ln59_fu_547_p1");
    sc_trace(mVcdFile, zext_ln54_fu_552_p1, "zext_ln54_fu_552_p1");
    sc_trace(mVcdFile, zext_ln48_fu_557_p1, "zext_ln48_fu_557_p1");
    sc_trace(mVcdFile, zext_ln43_fu_562_p1, "zext_ln43_fu_562_p1");
    sc_trace(mVcdFile, grp_fu_225_p0, "grp_fu_225_p0");
    sc_trace(mVcdFile, grp_fu_225_p1, "grp_fu_225_p1");
    sc_trace(mVcdFile, grp_fu_229_p1, "grp_fu_229_p1");
    sc_trace(mVcdFile, p_Result_3_fu_274_p4, "p_Result_3_fu_274_p4");
    sc_trace(mVcdFile, p_Result_2_fu_289_p4, "p_Result_2_fu_289_p4");
    sc_trace(mVcdFile, p_Result_1_fu_304_p4, "p_Result_1_fu_304_p4");
    sc_trace(mVcdFile, p_Result_s_fu_319_p4, "p_Result_s_fu_319_p4");
    sc_trace(mVcdFile, shl_ln_fu_346_p3, "shl_ln_fu_346_p3");
    sc_trace(mVcdFile, grp_fu_225_p2, "grp_fu_225_p2");
    sc_trace(mVcdFile, tmp_2_fu_373_p4, "tmp_2_fu_373_p4");
    sc_trace(mVcdFile, grp_fu_229_p2, "grp_fu_229_p2");
    sc_trace(mVcdFile, select_ln647_1_fu_391_p3, "select_ln647_1_fu_391_p3");
    sc_trace(mVcdFile, select_ln647_fu_383_p3, "select_ln647_fu_383_p3");
    sc_trace(mVcdFile, zext_ln647_fu_399_p1, "zext_ln647_fu_399_p1");
    sc_trace(mVcdFile, lshr_ln647_fu_403_p2, "lshr_ln647_fu_403_p2");
    sc_trace(mVcdFile, p_Result_7_fu_419_p3, "p_Result_7_fu_419_p3");
    sc_trace(mVcdFile, select_ln414_fu_438_p3, "select_ln414_fu_438_p3");
    sc_trace(mVcdFile, select_ln414_2_fu_450_p3, "select_ln414_2_fu_450_p3");
    sc_trace(mVcdFile, select_ln414_1_fu_444_p3, "select_ln414_1_fu_444_p3");
    sc_trace(mVcdFile, sub_ln414_1_fu_457_p2, "sub_ln414_1_fu_457_p2");
    sc_trace(mVcdFile, tmp_V_fu_432_p2, "tmp_V_fu_432_p2");
    sc_trace(mVcdFile, zext_ln414_fu_463_p1, "zext_ln414_fu_463_p1");
    sc_trace(mVcdFile, shl_ln414_fu_475_p2, "shl_ln414_fu_475_p2");
    sc_trace(mVcdFile, tmp_4_fu_481_p4, "tmp_4_fu_481_p4");
    sc_trace(mVcdFile, zext_ln414_1_fu_467_p1, "zext_ln414_1_fu_467_p1");
    sc_trace(mVcdFile, zext_ln414_2_fu_471_p1, "zext_ln414_2_fu_471_p1");
    sc_trace(mVcdFile, shl_ln414_1_fu_499_p2, "shl_ln414_1_fu_499_p2");
    sc_trace(mVcdFile, lshr_ln414_fu_505_p2, "lshr_ln414_fu_505_p2");
    sc_trace(mVcdFile, and_ln414_fu_511_p2, "and_ln414_fu_511_p2");
    sc_trace(mVcdFile, xor_ln414_fu_517_p2, "xor_ln414_fu_517_p2");
    sc_trace(mVcdFile, select_ln414_3_fu_491_p3, "select_ln414_3_fu_491_p3");
    sc_trace(mVcdFile, and_ln414_1_fu_523_p2, "and_ln414_1_fu_523_p2");
    sc_trace(mVcdFile, and_ln414_2_fu_529_p2, "and_ln414_2_fu_529_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_155, "ap_condition_155");
    sc_trace(mVcdFile, ap_condition_159, "ap_condition_159");
    sc_trace(mVcdFile, ap_condition_414, "ap_condition_414");
    sc_trace(mVcdFile, ap_condition_417, "ap_condition_417");
#endif

    }
    mHdltvinHandle.open("inOutFunction.hdltvin.dat");
    mHdltvoutHandle.open("inOutFunction.hdltvout.dat");
}

inOutFunction::~inOutFunction() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete sevenSegmentNumbers_U;
}

void inOutFunction::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_334_p2.read()))) {
        e_0_i_reg_192 = e_reg_583.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        e_0_i_reg_192 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_0))) {
        i_0_i_reg_214 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_0_i_reg_214 = i_reg_627.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_0))) {
        p_Val2_1_reg_203 = p_Val2_s_reg_182.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_Val2_1_reg_203 = dabble_V_3_fu_541_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_334_p2.read()))) {
        p_Val2_s_reg_182 = r_V_fu_413_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        p_Val2_s_reg_182 = dabble_V_fu_234_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_fu_334_p2.read()))) {
        add_ln19_1_reg_644 = add_ln19_1_fu_366_p2.read();
        add_ln19_reg_637 = add_ln19_fu_359_p2.read();
        trunc_ln647_reg_652 = trunc_ln647_fu_409_p1.read();
        zext_ln19_reg_632 = zext_ln19_fu_354_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        e_reg_583 = e_fu_244_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_627 = i_fu_340_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        icmp_ln895_reg_662 = icmp_ln895_fu_426_p2.read();
        p_Result_8_reg_667 = p_Result_8_fu_535_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0))) {
        tmp_1_reg_596 = pushButton_V.read().range(2, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_260_p3.read()))) {
        tmp_5_reg_600 = pushButton_V.read().range(3, 3);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0))) {
        tmp_reg_592 = pushButton_V.read().range(1, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1))) {
        trunc_ln791_reg_588 = trunc_ln791_fu_250_p1.read();
    }
}

void inOutFunction::thread_add_ln19_1_fu_366_p2() {
    add_ln19_1_fu_366_p2 = (!ap_const_lv6_10.is_01() || !zext_ln19_fu_354_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_10) + sc_biguint<6>(zext_ln19_fu_354_p1.read()));
}

void inOutFunction::thread_add_ln19_fu_359_p2() {
    add_ln19_fu_359_p2 = (!ap_const_lv6_13.is_01() || !zext_ln19_fu_354_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_13) + sc_biguint<6>(zext_ln19_fu_354_p1.read()));
}

void inOutFunction::thread_and_ln414_1_fu_523_p2() {
    and_ln414_1_fu_523_p2 = (p_Val2_1_reg_203.read() & xor_ln414_fu_517_p2.read());
}

void inOutFunction::thread_and_ln414_2_fu_529_p2() {
    and_ln414_2_fu_529_p2 = (select_ln414_3_fu_491_p3.read() & and_ln414_fu_511_p2.read());
}

void inOutFunction::thread_and_ln414_fu_511_p2() {
    and_ln414_fu_511_p2 = (shl_ln414_1_fu_499_p2.read() & lshr_ln414_fu_505_p2.read());
}

void inOutFunction::thread_anodes_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_1))) {
        anodes_V = ap_const_lv4_E;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_592.read()))) {
        anodes_V = ap_const_lv4_D;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_reg_592.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_1_reg_596.read()))) {
        anodes_V = ap_const_lv4_B;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_reg_592.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_reg_596.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_reg_600.read()))) {
        anodes_V = ap_const_lv4_7;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_260_p3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_267_p3.read()))) {
        anodes_V = ap_const_lv4_F;
    } else {
        anodes_V = "XXXX";
    }
}

void inOutFunction::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void inOutFunction::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void inOutFunction::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void inOutFunction::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void inOutFunction::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void inOutFunction::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void inOutFunction::thread_ap_condition_155() {
    ap_condition_155 = (esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_reg_592.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_reg_596.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_reg_600.read()));
}

void inOutFunction::thread_ap_condition_159() {
    ap_condition_159 = (esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_reg_592.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_1_reg_596.read()));
}

void inOutFunction::thread_ap_condition_414() {
    ap_condition_414 = (esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_260_p3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_fu_267_p3.read()));
}

void inOutFunction::thread_ap_condition_417() {
    ap_condition_417 = (esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_1_fu_260_p3.read()));
}

void inOutFunction::thread_dabble_V_3_fu_541_p3() {
    dabble_V_3_fu_541_p3 = (!icmp_ln895_reg_662.read()[0].is_01())? sc_lv<36>(): ((icmp_ln895_reg_662.read()[0].to_bool())? p_Result_8_reg_667.read(): p_Val2_1_reg_203.read());
}

void inOutFunction::thread_dabble_V_fu_234_p1() {
    dabble_V_fu_234_p1 = esl_zext<36,16>(inNumber_V.read());
}

void inOutFunction::thread_e_fu_244_p2() {
    e_fu_244_p2 = (!e_0_i_reg_192.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(e_0_i_reg_192.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void inOutFunction::thread_grp_fu_225_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_225_p0 = add_ln19_1_reg_644.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_225_p0 = add_ln19_1_fu_366_p2.read();
    } else {
        grp_fu_225_p0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void inOutFunction::thread_grp_fu_225_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_225_p1 = add_ln19_reg_637.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_225_p1 = add_ln19_fu_359_p2.read();
    } else {
        grp_fu_225_p1 =  (sc_lv<6>) ("XXXXXX");
    }
}

void inOutFunction::thread_grp_fu_225_p2() {
    grp_fu_225_p2 = (!grp_fu_225_p0.read().is_01() || !grp_fu_225_p1.read().is_01())? sc_lv<1>(): (sc_biguint<6>(grp_fu_225_p0.read()) > sc_biguint<6>(grp_fu_225_p1.read()));
}

void inOutFunction::thread_grp_fu_229_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_229_p1 = zext_ln19_reg_632.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_229_p1 = zext_ln19_fu_354_p1.read();
    } else {
        grp_fu_229_p1 =  (sc_lv<6>) ("XXXXXX");
    }
}

void inOutFunction::thread_grp_fu_229_p2() {
    grp_fu_229_p2 = (!ap_const_lv6_13.is_01() || !grp_fu_229_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_13) - sc_biguint<6>(grp_fu_229_p1.read()));
}

void inOutFunction::thread_i_fu_340_p2() {
    i_fu_340_p2 = (!i_0_i_reg_214.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_i_reg_214.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void inOutFunction::thread_icmp_ln15_fu_238_p2() {
    icmp_ln15_fu_238_p2 = (!e_0_i_reg_192.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(e_0_i_reg_192.read() == ap_const_lv5_10);
}

void inOutFunction::thread_icmp_ln17_fu_334_p2() {
    icmp_ln17_fu_334_p2 = (!i_0_i_reg_214.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_214.read() == ap_const_lv3_5);
}

void inOutFunction::thread_icmp_ln895_fu_426_p2() {
    icmp_ln895_fu_426_p2 = (!p_Result_7_fu_419_p3.read().is_01() || !ap_const_lv36_4.is_01())? sc_lv<1>(): (sc_biguint<36>(p_Result_7_fu_419_p3.read()) > sc_biguint<36>(ap_const_lv36_4));
}

void inOutFunction::thread_lshr_ln414_fu_505_p2() {
    lshr_ln414_fu_505_p2 = (!zext_ln414_2_fu_471_p1.read().is_01())? sc_lv<36>(): ap_const_lv36_FFFFFFFFF >> (unsigned short)zext_ln414_2_fu_471_p1.read().to_uint();
}

void inOutFunction::thread_lshr_ln647_fu_403_p2() {
    lshr_ln647_fu_403_p2 = (!zext_ln647_fu_399_p1.read().is_01())? sc_lv<36>(): select_ln647_fu_383_p3.read() >> (unsigned short)zext_ln647_fu_399_p1.read().to_uint();
}

void inOutFunction::thread_outputSegments_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        if (esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_1)) {
            outputSegments_V = zext_ln43_fu_562_p1.read();
        } else if ((esl_seteq<1,1,1>(trunc_ln791_reg_588.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_592.read()))) {
            outputSegments_V = zext_ln48_fu_557_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_159.read(), ap_const_boolean_1)) {
            outputSegments_V = zext_ln54_fu_552_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_155.read(), ap_const_boolean_1)) {
            outputSegments_V = zext_ln59_fu_547_p1.read();
        } else {
            outputSegments_V =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        outputSegments_V =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void inOutFunction::thread_p_Result_1_fu_304_p4() {
    p_Result_1_fu_304_p4 = p_Val2_s_reg_182.read().range(23, 20);
}

void inOutFunction::thread_p_Result_2_fu_289_p4() {
    p_Result_2_fu_289_p4 = p_Val2_s_reg_182.read().range(27, 24);
}

void inOutFunction::thread_p_Result_3_fu_274_p4() {
    p_Result_3_fu_274_p4 = p_Val2_s_reg_182.read().range(31, 28);
}

void inOutFunction::thread_p_Result_7_fu_419_p3() {
    p_Result_7_fu_419_p3 = esl_concat<32,4>(ap_const_lv32_0, trunc_ln647_reg_652.read());
}

void inOutFunction::thread_p_Result_8_fu_535_p2() {
    p_Result_8_fu_535_p2 = (and_ln414_1_fu_523_p2.read() | and_ln414_2_fu_529_p2.read());
}

void inOutFunction::thread_p_Result_s_fu_319_p4() {
    p_Result_s_fu_319_p4 = p_Val2_s_reg_182.read().range(19, 16);
}

void inOutFunction::thread_r_V_fu_413_p2() {
    r_V_fu_413_p2 = (!ap_const_lv36_1.is_01())? sc_lv<36>(): p_Val2_1_reg_203.read() << (unsigned short)ap_const_lv36_1.to_uint();
}

void inOutFunction::thread_select_ln414_1_fu_444_p3() {
    select_ln414_1_fu_444_p3 = (!grp_fu_225_p2.read()[0].is_01())? sc_lv<6>(): ((grp_fu_225_p2.read()[0].to_bool())? add_ln19_reg_637.read(): add_ln19_1_reg_644.read());
}

void inOutFunction::thread_select_ln414_2_fu_450_p3() {
    select_ln414_2_fu_450_p3 = (!grp_fu_225_p2.read()[0].is_01())? sc_lv<6>(): ((grp_fu_225_p2.read()[0].to_bool())? grp_fu_229_p2.read(): add_ln19_1_reg_644.read());
}

void inOutFunction::thread_select_ln414_3_fu_491_p3() {
    select_ln414_3_fu_491_p3 = (!grp_fu_225_p2.read()[0].is_01())? sc_lv<36>(): ((grp_fu_225_p2.read()[0].to_bool())? tmp_4_fu_481_p4.read(): shl_ln414_fu_475_p2.read());
}

void inOutFunction::thread_select_ln414_fu_438_p3() {
    select_ln414_fu_438_p3 = (!grp_fu_225_p2.read()[0].is_01())? sc_lv<6>(): ((grp_fu_225_p2.read()[0].to_bool())? add_ln19_1_reg_644.read(): add_ln19_reg_637.read());
}

void inOutFunction::thread_select_ln647_1_fu_391_p3() {
    select_ln647_1_fu_391_p3 = (!grp_fu_225_p2.read()[0].is_01())? sc_lv<6>(): ((grp_fu_225_p2.read()[0].to_bool())? grp_fu_229_p2.read(): add_ln19_1_fu_366_p2.read());
}

void inOutFunction::thread_select_ln647_fu_383_p3() {
    select_ln647_fu_383_p3 = (!grp_fu_225_p2.read()[0].is_01())? sc_lv<36>(): ((grp_fu_225_p2.read()[0].to_bool())? tmp_2_fu_373_p4.read(): p_Val2_1_reg_203.read());
}

void inOutFunction::thread_sevenSegmentNumbers_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1))) {
        if (esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_1)) {
            sevenSegmentNumbers_address0 =  (sc_lv<4>) (zext_ln681_fu_329_p1.read());
        } else if ((esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_fu_253_p3.read()))) {
            sevenSegmentNumbers_address0 =  (sc_lv<4>) (zext_ln681_1_fu_314_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_417.read(), ap_const_boolean_1)) {
            sevenSegmentNumbers_address0 =  (sc_lv<4>) (zext_ln681_2_fu_299_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_414.read(), ap_const_boolean_1)) {
            sevenSegmentNumbers_address0 =  (sc_lv<4>) (zext_ln681_3_fu_284_p1.read());
        } else {
            sevenSegmentNumbers_address0 = "XXXX";
        }
    } else {
        sevenSegmentNumbers_address0 = "XXXX";
    }
}

void inOutFunction::thread_sevenSegmentNumbers_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_260_p3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_fu_267_p3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_fu_253_p3.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_1_fu_260_p3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_fu_253_p3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(trunc_ln791_fu_250_p1.read(), ap_const_lv1_1)))) {
        sevenSegmentNumbers_ce0 = ap_const_logic_1;
    } else {
        sevenSegmentNumbers_ce0 = ap_const_logic_0;
    }
}

void inOutFunction::thread_shl_ln414_1_fu_499_p2() {
    shl_ln414_1_fu_499_p2 = (!zext_ln414_1_fu_467_p1.read().is_01())? sc_lv<36>(): ap_const_lv36_FFFFFFFFF << (unsigned short)zext_ln414_1_fu_467_p1.read().to_uint();
}

void inOutFunction::thread_shl_ln414_fu_475_p2() {
    shl_ln414_fu_475_p2 = (!zext_ln414_fu_463_p1.read().is_01())? sc_lv<36>(): tmp_V_fu_432_p2.read() << (unsigned short)zext_ln414_fu_463_p1.read().to_uint();
}

void inOutFunction::thread_shl_ln_fu_346_p3() {
    shl_ln_fu_346_p3 = esl_concat<3,2>(i_0_i_reg_214.read(), ap_const_lv2_0);
}

void inOutFunction::thread_sub_ln414_1_fu_457_p2() {
    sub_ln414_1_fu_457_p2 = (!ap_const_lv6_23.is_01() || !select_ln414_fu_438_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_23) - sc_biguint<6>(select_ln414_fu_438_p3.read()));
}

void inOutFunction::thread_tmp_1_fu_260_p3() {
    tmp_1_fu_260_p3 = pushButton_V.read().range(2, 2);
}

void inOutFunction::thread_tmp_2_fu_373_p4() {
    tmp_2_fu_373_p4 = p_Val2_1_reg_203.read().range(0, 35);
}

void inOutFunction::thread_tmp_4_fu_481_p4() {
    tmp_4_fu_481_p4 = shl_ln414_fu_475_p2.read().range(0, 35);
}

void inOutFunction::thread_tmp_5_fu_267_p3() {
    tmp_5_fu_267_p3 = pushButton_V.read().range(3, 3);
}

void inOutFunction::thread_tmp_V_fu_432_p2() {
    tmp_V_fu_432_p2 = (!ap_const_lv36_3.is_01() || !p_Result_7_fu_419_p3.read().is_01())? sc_lv<36>(): (sc_biguint<36>(ap_const_lv36_3) + sc_biguint<36>(p_Result_7_fu_419_p3.read()));
}

void inOutFunction::thread_tmp_fu_253_p3() {
    tmp_fu_253_p3 = pushButton_V.read().range(1, 1);
}

void inOutFunction::thread_trunc_ln647_fu_409_p1() {
    trunc_ln647_fu_409_p1 = lshr_ln647_fu_403_p2.read().range(4-1, 0);
}

void inOutFunction::thread_trunc_ln791_fu_250_p1() {
    trunc_ln791_fu_250_p1 = pushButton_V.read().range(1-1, 0);
}

void inOutFunction::thread_xor_ln414_fu_517_p2() {
    xor_ln414_fu_517_p2 = (and_ln414_fu_511_p2.read() ^ ap_const_lv36_FFFFFFFFF);
}

void inOutFunction::thread_zext_ln19_fu_354_p1() {
    zext_ln19_fu_354_p1 = esl_zext<6,5>(shl_ln_fu_346_p3.read());
}

void inOutFunction::thread_zext_ln414_1_fu_467_p1() {
    zext_ln414_1_fu_467_p1 = esl_zext<36,6>(select_ln414_1_fu_444_p3.read());
}

void inOutFunction::thread_zext_ln414_2_fu_471_p1() {
    zext_ln414_2_fu_471_p1 = esl_zext<36,6>(sub_ln414_1_fu_457_p2.read());
}

void inOutFunction::thread_zext_ln414_fu_463_p1() {
    zext_ln414_fu_463_p1 = esl_zext<36,6>(select_ln414_2_fu_450_p3.read());
}

void inOutFunction::thread_zext_ln43_fu_562_p1() {
    zext_ln43_fu_562_p1 = esl_zext<8,7>(sevenSegmentNumbers_q0.read());
}

void inOutFunction::thread_zext_ln48_fu_557_p1() {
    zext_ln48_fu_557_p1 = esl_zext<8,7>(sevenSegmentNumbers_q0.read());
}

void inOutFunction::thread_zext_ln54_fu_552_p1() {
    zext_ln54_fu_552_p1 = esl_zext<8,7>(sevenSegmentNumbers_q0.read());
}

void inOutFunction::thread_zext_ln59_fu_547_p1() {
    zext_ln59_fu_547_p1 = esl_zext<8,7>(sevenSegmentNumbers_q0.read());
}

void inOutFunction::thread_zext_ln647_fu_399_p1() {
    zext_ln647_fu_399_p1 = esl_zext<36,6>(select_ln647_1_fu_391_p3.read());
}

void inOutFunction::thread_zext_ln681_1_fu_314_p1() {
    zext_ln681_1_fu_314_p1 = esl_zext<64,4>(p_Result_1_fu_304_p4.read());
}

void inOutFunction::thread_zext_ln681_2_fu_299_p1() {
    zext_ln681_2_fu_299_p1 = esl_zext<64,4>(p_Result_2_fu_289_p4.read());
}

void inOutFunction::thread_zext_ln681_3_fu_284_p1() {
    zext_ln681_3_fu_284_p1 = esl_zext<64,4>(p_Result_3_fu_274_p4.read());
}

void inOutFunction::thread_zext_ln681_fu_329_p1() {
    zext_ln681_fu_329_p1 = esl_zext<64,4>(p_Result_s_fu_319_p4.read());
}

void inOutFunction::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_238_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_334_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

void inOutFunction::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inNumber_V\" :  \"" << inNumber_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pushButton_V\" :  \"" << pushButton_V.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"anodes_V\" :  \"" << anodes_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputSegments_V\" :  \"" << outputSegments_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

