// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _inout_inlineoff_HH_
#define _inout_inlineoff_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "andGate.h"
#include "orGate.h"
#include "notGate.h"

namespace ap_rtl {

struct inout_inlineoff : public sc_module {
    // Port declarations 4
    sc_in< sc_logic > a;
    sc_in< sc_logic > b;
    sc_in< sc_logic > c;
    sc_out< sc_logic > d;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    inout_inlineoff(sc_module_name name);
    SC_HAS_PROCESS(inout_inlineoff);

    ~inout_inlineoff();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    andGate* tmp_andGate_fu_59;
    orGate* tmp_2_orGate_fu_67;
    notGate* tmp_1_notGate_fu_75;
    sc_signal< sc_logic > tmp_andGate_fu_59_ap_ready;
    sc_signal< sc_lv<1> > tmp_andGate_fu_59_ap_return;
    sc_signal< sc_logic > tmp_2_orGate_fu_67_ap_ready;
    sc_signal< sc_logic > tmp_2_orGate_fu_67_a;
    sc_signal< sc_logic > tmp_2_orGate_fu_67_b;
    sc_signal< sc_lv<1> > tmp_2_orGate_fu_67_ap_return;
    sc_signal< sc_logic > tmp_1_notGate_fu_75_ap_ready;
    sc_signal< sc_lv<1> > tmp_1_notGate_fu_75_ap_return;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_d();
    void thread_tmp_2_orGate_fu_67_a();
    void thread_tmp_2_orGate_fu_67_b();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
