// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _orGate_HH_
#define _orGate_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct orGate : public sc_module {
    // Port declarations 4
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > a;
    sc_in< sc_logic > b;
    sc_out< sc_lv<1> > ap_return;


    // Module declarations
    orGate(sc_module_name name);
    SC_HAS_PROCESS(orGate);

    ~orGate();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > or_ln17_fu_18_p0;
    sc_signal< sc_lv<1> > or_ln17_fu_18_p1;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_or_ln17_fu_18_p0();
    void thread_or_ln17_fu_18_p1();
};

}

using namespace ap_rtl;

#endif
