// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _inOutFunction_HH_
#define _inOutFunction_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "delay.h"
#include "inOutFunction_srecud.h"
#include "inOutFunction_sredEe.h"
#include "inOutFunction_sreeOg.h"
#include "inOutFunction_mulfYi.h"
#include "inOutFunction_sevbkb.h"

namespace ap_rtl {

struct inOutFunction : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > digit;
    sc_out< sc_logic > digit_ap_vld;
    sc_out< sc_lv<8> > anode;
    sc_out< sc_logic > anode_ap_vld;
    sc_in< sc_lv<32> > firstNumber;
    sc_in< sc_lv<32> > secondNumber;


    // Module declarations
    inOutFunction(sc_module_name name);
    SC_HAS_PROCESS(inOutFunction);

    ~inOutFunction();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    inOutFunction_sevbkb* sevenSegmentNumbers_U;
    delay* grp_delay_fu_165;
    inOutFunction_srecud<1,36,32,8,32>* inOutFunction_srecud_U1;
    inOutFunction_sredEe<1,36,32,5,32>* inOutFunction_sredEe_U2;
    inOutFunction_sreeOg<1,36,32,11,32>* inOutFunction_sreeOg_U3;
    inOutFunction_mulfYi<1,1,13,11,24>* inOutFunction_mulfYi_U4;
    sc_signal< sc_lv<41> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > sevenSegmentNumbers_address0;
    sc_signal< sc_logic > sevenSegmentNumbers_ce0;
    sc_signal< sc_lv<7> > sevenSegmentNumbers_q0;
    sc_signal< sc_lv<32> > add_ln66_fu_171_p2;
    sc_signal< sc_lv<32> > add_ln66_reg_454;
    sc_signal< sc_lv<1> > tmp_11_reg_462;
    sc_signal< sc_lv<65> > mul_ln52_fu_204_p2;
    sc_signal< sc_lv<65> > mul_ln52_reg_468;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<23> > tmp_13_reg_473;
    sc_signal< sc_lv<32> > select_ln52_1_fu_255_p3;
    sc_signal< sc_lv<32> > select_ln52_1_reg_478;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<7> > sevenSegmentNumbers_7_reg_488;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<8> > trunc_ln42_fu_266_p1;
    sc_signal< sc_lv<8> > trunc_ln42_reg_493;
    sc_signal< sc_logic > ap_CS_fsm_state36;
    sc_signal< sc_lv<1> > tmp_6_reg_498;
    sc_signal< sc_logic > ap_CS_fsm_state37;
    sc_signal< sc_logic > grp_delay_fu_165_ap_ready;
    sc_signal< sc_logic > grp_delay_fu_165_ap_done;
    sc_signal< sc_lv<17> > trunc_ln42_1_fu_292_p1;
    sc_signal< sc_lv<17> > trunc_ln42_1_reg_509;
    sc_signal< sc_lv<6> > tmp_reg_514;
    sc_signal< sc_lv<11> > trunc_ln47_fu_306_p1;
    sc_signal< sc_lv<11> > trunc_ln47_reg_519;
    sc_signal< sc_lv<1> > tmp_8_reg_524;
    sc_signal< sc_logic > ap_CS_fsm_state38;
    sc_signal< sc_lv<23> > trunc_ln47_1_fu_373_p1;
    sc_signal< sc_lv<23> > trunc_ln47_1_reg_535;
    sc_signal< sc_lv<6> > tmp_10_reg_540;
    sc_signal< sc_logic > ap_CS_fsm_state39;
    sc_signal< sc_logic > grp_delay_fu_165_ap_start;
    sc_signal< sc_logic > grp_delay_fu_165_ap_idle;
    sc_signal< sc_logic > grp_delay_fu_165_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state34;
    sc_signal< sc_logic > ap_CS_fsm_state40;
    sc_signal< sc_logic > ap_CS_fsm_state35;
    sc_signal< sc_logic > ap_CS_fsm_state41;
    sc_signal< sc_lv<64> > sext_ln52_fu_262_p1;
    sc_signal< sc_lv<64> > sext_ln36_fu_278_p1;
    sc_signal< sc_lv<64> > sext_ln42_fu_365_p1;
    sc_signal< sc_lv<64> > sext_ln47_fu_432_p1;
    sc_signal< sc_lv<8> > zext_ln36_fu_318_p1;
    sc_signal< sc_lv<8> > zext_ln42_fu_385_p1;
    sc_signal< sc_lv<8> > zext_ln47_fu_437_p1;
    sc_signal< sc_lv<8> > zext_ln52_fu_442_p1;
    sc_signal< sc_lv<8> > grp_fu_177_p1;
    sc_signal< sc_lv<5> > grp_fu_191_p1;
    sc_signal< sc_lv<11> > grp_fu_196_p1;
    sc_signal< sc_lv<32> > mul_ln52_fu_204_p1;
    sc_signal< sc_lv<65> > sub_ln52_fu_220_p2;
    sc_signal< sc_lv<23> > tmp_12_fu_225_p4;
    sc_signal< sc_lv<32> > sext_ln52_2_fu_235_p1;
    sc_signal< sc_lv<32> > sext_ln52_3_fu_239_p1;
    sc_signal< sc_lv<32> > select_ln52_fu_242_p3;
    sc_signal< sc_lv<32> > sub_ln52_1_fu_249_p2;
    sc_signal< sc_lv<32> > grp_fu_177_p2;
    sc_signal< sc_lv<32> > grp_fu_191_p2;
    sc_signal< sc_lv<8> > mul_ln42_fu_286_p1;
    sc_signal< sc_lv<18> > mul_ln42_fu_286_p2;
    sc_signal< sc_lv<32> > grp_fu_196_p2;
    sc_signal< sc_lv<17> > sub_ln42_fu_323_p2;
    sc_signal< sc_lv<5> > tmp_7_fu_328_p4;
    sc_signal< sc_lv<8> > sext_ln42_2_fu_338_p1;
    sc_signal< sc_lv<8> > sext_ln42_3_fu_342_p1;
    sc_signal< sc_lv<8> > select_ln42_fu_345_p3;
    sc_signal< sc_lv<8> > sub_ln42_1_fu_352_p2;
    sc_signal< sc_lv<8> > select_ln42_1_fu_358_p3;
    sc_signal< sc_lv<24> > mul_ln47_fu_446_p2;
    sc_signal< sc_lv<23> > sub_ln47_fu_390_p2;
    sc_signal< sc_lv<5> > tmp_9_fu_395_p4;
    sc_signal< sc_lv<11> > sext_ln47_2_fu_405_p1;
    sc_signal< sc_lv<11> > sext_ln47_3_fu_409_p1;
    sc_signal< sc_lv<11> > select_ln47_fu_412_p3;
    sc_signal< sc_lv<11> > sub_ln47_1_fu_419_p2;
    sc_signal< sc_lv<11> > select_ln47_1_fu_425_p3;
    sc_signal< sc_lv<13> > mul_ln47_fu_446_p0;
    sc_signal< sc_logic > grp_fu_177_ap_start;
    sc_signal< sc_logic > grp_fu_177_ap_done;
    sc_signal< sc_logic > grp_fu_177_ce;
    sc_signal< sc_logic > grp_fu_191_ap_start;
    sc_signal< sc_logic > grp_fu_191_ap_done;
    sc_signal< sc_logic > grp_fu_191_ce;
    sc_signal< sc_logic > grp_fu_196_ap_start;
    sc_signal< sc_logic > grp_fu_196_ap_done;
    sc_signal< sc_logic > grp_fu_196_ce;
    sc_signal< sc_lv<41> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<41> ap_ST_fsm_state1;
    static const sc_lv<41> ap_ST_fsm_state2;
    static const sc_lv<41> ap_ST_fsm_state3;
    static const sc_lv<41> ap_ST_fsm_state4;
    static const sc_lv<41> ap_ST_fsm_state5;
    static const sc_lv<41> ap_ST_fsm_state6;
    static const sc_lv<41> ap_ST_fsm_state7;
    static const sc_lv<41> ap_ST_fsm_state8;
    static const sc_lv<41> ap_ST_fsm_state9;
    static const sc_lv<41> ap_ST_fsm_state10;
    static const sc_lv<41> ap_ST_fsm_state11;
    static const sc_lv<41> ap_ST_fsm_state12;
    static const sc_lv<41> ap_ST_fsm_state13;
    static const sc_lv<41> ap_ST_fsm_state14;
    static const sc_lv<41> ap_ST_fsm_state15;
    static const sc_lv<41> ap_ST_fsm_state16;
    static const sc_lv<41> ap_ST_fsm_state17;
    static const sc_lv<41> ap_ST_fsm_state18;
    static const sc_lv<41> ap_ST_fsm_state19;
    static const sc_lv<41> ap_ST_fsm_state20;
    static const sc_lv<41> ap_ST_fsm_state21;
    static const sc_lv<41> ap_ST_fsm_state22;
    static const sc_lv<41> ap_ST_fsm_state23;
    static const sc_lv<41> ap_ST_fsm_state24;
    static const sc_lv<41> ap_ST_fsm_state25;
    static const sc_lv<41> ap_ST_fsm_state26;
    static const sc_lv<41> ap_ST_fsm_state27;
    static const sc_lv<41> ap_ST_fsm_state28;
    static const sc_lv<41> ap_ST_fsm_state29;
    static const sc_lv<41> ap_ST_fsm_state30;
    static const sc_lv<41> ap_ST_fsm_state31;
    static const sc_lv<41> ap_ST_fsm_state32;
    static const sc_lv<41> ap_ST_fsm_state33;
    static const sc_lv<41> ap_ST_fsm_state34;
    static const sc_lv<41> ap_ST_fsm_state35;
    static const sc_lv<41> ap_ST_fsm_state36;
    static const sc_lv<41> ap_ST_fsm_state37;
    static const sc_lv<41> ap_ST_fsm_state38;
    static const sc_lv<41> ap_ST_fsm_state39;
    static const sc_lv<41> ap_ST_fsm_state40;
    static const sc_lv<41> ap_ST_fsm_state41;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<32> ap_const_lv32_21;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<8> ap_const_lv8_8;
    static const sc_lv<8> ap_const_lv8_4;
    static const sc_lv<8> ap_const_lv8_2;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_64;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_3E8;
    static const sc_lv<65> ap_const_lv65_10624DD30;
    static const sc_lv<32> ap_const_lv32_2A;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<65> ap_const_lv65_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<18> ap_const_lv18_19A;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<24> ap_const_lv24_A3E;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln66_fu_171_p2();
    void thread_anode();
    void thread_anode_ap_vld();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state34();
    void thread_ap_CS_fsm_state35();
    void thread_ap_CS_fsm_state36();
    void thread_ap_CS_fsm_state37();
    void thread_ap_CS_fsm_state38();
    void thread_ap_CS_fsm_state39();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state40();
    void thread_ap_CS_fsm_state41();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_digit();
    void thread_digit_ap_vld();
    void thread_grp_delay_fu_165_ap_start();
    void thread_grp_fu_177_ap_start();
    void thread_grp_fu_177_ce();
    void thread_grp_fu_177_p1();
    void thread_grp_fu_191_ap_start();
    void thread_grp_fu_191_ce();
    void thread_grp_fu_191_p1();
    void thread_grp_fu_196_ap_start();
    void thread_grp_fu_196_ce();
    void thread_grp_fu_196_p1();
    void thread_mul_ln42_fu_286_p1();
    void thread_mul_ln42_fu_286_p2();
    void thread_mul_ln47_fu_446_p0();
    void thread_mul_ln52_fu_204_p1();
    void thread_mul_ln52_fu_204_p2();
    void thread_select_ln42_1_fu_358_p3();
    void thread_select_ln42_fu_345_p3();
    void thread_select_ln47_1_fu_425_p3();
    void thread_select_ln47_fu_412_p3();
    void thread_select_ln52_1_fu_255_p3();
    void thread_select_ln52_fu_242_p3();
    void thread_sevenSegmentNumbers_address0();
    void thread_sevenSegmentNumbers_ce0();
    void thread_sext_ln36_fu_278_p1();
    void thread_sext_ln42_2_fu_338_p1();
    void thread_sext_ln42_3_fu_342_p1();
    void thread_sext_ln42_fu_365_p1();
    void thread_sext_ln47_2_fu_405_p1();
    void thread_sext_ln47_3_fu_409_p1();
    void thread_sext_ln47_fu_432_p1();
    void thread_sext_ln52_2_fu_235_p1();
    void thread_sext_ln52_3_fu_239_p1();
    void thread_sext_ln52_fu_262_p1();
    void thread_sub_ln42_1_fu_352_p2();
    void thread_sub_ln42_fu_323_p2();
    void thread_sub_ln47_1_fu_419_p2();
    void thread_sub_ln47_fu_390_p2();
    void thread_sub_ln52_1_fu_249_p2();
    void thread_sub_ln52_fu_220_p2();
    void thread_tmp_12_fu_225_p4();
    void thread_tmp_7_fu_328_p4();
    void thread_tmp_9_fu_395_p4();
    void thread_trunc_ln42_1_fu_292_p1();
    void thread_trunc_ln42_fu_266_p1();
    void thread_trunc_ln47_1_fu_373_p1();
    void thread_trunc_ln47_fu_306_p1();
    void thread_zext_ln36_fu_318_p1();
    void thread_zext_ln42_fu_385_p1();
    void thread_zext_ln47_fu_437_p1();
    void thread_zext_ln52_fu_442_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
