// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _in_out_HH_
#define _in_out_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct in_out : public sc_module {
    // Port declarations 2
    sc_in< sc_lv<16> > input_r;
    sc_out< sc_lv<16> > output_r;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    in_out(sc_module_name name);
    SC_HAS_PROCESS(in_out);

    ~in_out();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_output_r();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
