# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/usr/Workspaces/HLS/Ejercicios/Seccion5/punto1-vivado/punto1-vivado.srcs/sources_1/bd/design_1/ip/design_1_in_out_0_0/design_1_in_out_0_0.xci
# IP: The module: 'design_1_in_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/usr/Workspaces/HLS/Ejercicios/Seccion5/punto1-vivado/punto1-vivado.srcs/sources_1/bd/design_1/ip/design_1_in_out_0_0/constraints/in_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_in_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/usr/Workspaces/HLS/Ejercicios/Seccion5/punto1-vivado/punto1-vivado.srcs/sources_1/bd/design_1/ip/design_1_in_out_0_0/design_1_in_out_0_0.xci
# IP: The module: 'design_1_in_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/usr/Workspaces/HLS/Ejercicios/Seccion5/punto1-vivado/punto1-vivado.srcs/sources_1/bd/design_1/ip/design_1_in_out_0_0/constraints/in_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_in_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
