// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _inOutFunction_HH_
#define _inOutFunction_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "inOutFunction_addbkb.h"

namespace ap_rtl {

struct inOutFunction : public sc_module {
    // Port declarations 5
    sc_in< sc_lv<32> > a;
    sc_in< sc_lv<32> > b;
    sc_in< sc_lv<32> > c;
    sc_in< sc_lv<32> > d;
    sc_out< sc_lv<32> > f;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    inOutFunction(sc_module_name name);
    SC_HAS_PROCESS(inOutFunction);

    ~inOutFunction();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    inOutFunction_addbkb<1,1,32,32,32>* inOutFunction_addbkb_U1;
    sc_signal< sc_lv<32> > t_4_fu_101_p2;
    sc_signal< sc_lv<32> > t_fu_71_p0;
    sc_signal< sc_lv<32> > t_fu_71_p1;
    sc_signal< sc_lv<32> > t_1_fu_77_p0;
    sc_signal< sc_lv<32> > t_1_fu_77_p1;
    sc_signal< sc_lv<32> > t_1_fu_77_p2;
    sc_signal< sc_lv<32> > t_fu_71_p2;
    sc_signal< sc_lv<32> > add_ln15_fu_89_p0;
    sc_signal< sc_lv<32> > add_ln15_fu_89_p1;
    sc_signal< sc_lv<32> > add_ln15_fu_89_p2;
    sc_signal< sc_lv<32> > t_3_fu_95_p1;
    sc_signal< sc_lv<32> > t_4_fu_101_p0;
    sc_signal< sc_lv<32> > t_4_fu_101_p1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_add_ln15_fu_89_p0();
    void thread_add_ln15_fu_89_p1();
    void thread_add_ln15_fu_89_p2();
    void thread_f();
    void thread_t_1_fu_77_p0();
    void thread_t_1_fu_77_p1();
    void thread_t_1_fu_77_p2();
    void thread_t_3_fu_95_p1();
    void thread_t_4_fu_101_p0();
    void thread_t_4_fu_101_p1();
    void thread_t_fu_71_p0();
    void thread_t_fu_71_p1();
    void thread_t_fu_71_p2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
