// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _inOutFunction_HH_
#define _inOutFunction_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "mul.h"

namespace ap_rtl {

struct inOutFunction : public sc_module {
    // Port declarations 5
    sc_in< sc_lv<32> > a;
    sc_in< sc_lv<32> > b;
    sc_in< sc_lv<32> > c;
    sc_in< sc_lv<32> > d;
    sc_out< sc_lv<32> > f;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    inOutFunction(sc_module_name name);
    SC_HAS_PROCESS(inOutFunction);

    ~inOutFunction();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mul* v_mul_fu_71;
    mul* w_mul_fu_79;
    mul* x_mul_fu_87;
    mul* y_mul_fu_95;
    sc_signal< sc_logic > v_mul_fu_71_ap_ready;
    sc_signal< sc_lv<32> > v_mul_fu_71_ap_return;
    sc_signal< sc_logic > w_mul_fu_79_ap_ready;
    sc_signal< sc_lv<32> > w_mul_fu_79_ap_return;
    sc_signal< sc_logic > x_mul_fu_87_ap_ready;
    sc_signal< sc_lv<32> > x_mul_fu_87_ap_return;
    sc_signal< sc_logic > y_mul_fu_95_ap_ready;
    sc_signal< sc_lv<32> > y_mul_fu_95_ap_return;
    sc_signal< sc_lv<32> > add_ln36_2_fu_109_p2;
    sc_signal< sc_lv<32> > add_ln36_1_fu_103_p2;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_add_ln36_1_fu_103_p2();
    void thread_add_ln36_2_fu_109_p2();
    void thread_f();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
