// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module notGate (
        ap_ready,
        a,
        ap_return
);


output   ap_ready;
input   a;
output  [0:0] ap_return;

wire   [0:0] xor_ln11_fu_12_p0;

assign ap_ready = 1'b1;

assign ap_return = (xor_ln11_fu_12_p0 ^ 1'd1);

assign xor_ln11_fu_12_p0 = a;

endmodule //notGate
