// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inOutFunction,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2020_1}" *)

module inOutFunction (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        r1_V,
        r1_V_ap_vld,
        r2_V,
        r2_V_ap_vld,
        r3_V,
        r3_V_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] r1_V;
output   r1_V_ap_vld;
output  [12:0] r2_V;
output   r2_V_ap_vld;
output  [12:0] r3_V;
output   r3_V_ap_vld;

reg r1_V_ap_vld;
reg r2_V_ap_vld;
reg r3_V_ap_vld;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        r1_V_ap_vld = 1'b1;
    end else begin
        r1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        r2_V_ap_vld = 1'b1;
    end else begin
        r2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        r3_V_ap_vld = 1'b1;
    end else begin
        r3_V_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign r1_V = 13'd64;

assign r2_V = 13'd4160;

assign r3_V = 13'd8188;

endmodule //inOutFunction
