// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inOutFunction,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=35.472000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=4271,HLS_VERSION=2020_1}" *)

module inOutFunction (
        a,
        b,
        c,
        d,
        f
);


input  [31:0] a;
input  [31:0] b;
input  [31:0] c;
input  [31:0] d;
output  [31:0] f;

wire    v_mul_fu_71_ap_ready;
wire   [31:0] v_mul_fu_71_ap_return;
wire    w_mul_fu_79_ap_ready;
wire   [31:0] w_mul_fu_79_ap_return;
wire    x_mul_fu_87_ap_ready;
wire   [31:0] x_mul_fu_87_ap_return;
wire    y_mul_fu_95_ap_ready;
wire   [31:0] y_mul_fu_95_ap_return;
wire   [31:0] add_ln36_2_fu_109_p2;
wire   [31:0] add_ln36_1_fu_103_p2;

mul v_mul_fu_71(
    .ap_ready(v_mul_fu_71_ap_ready),
    .a(a),
    .b(b),
    .ap_return(v_mul_fu_71_ap_return)
);

mul w_mul_fu_79(
    .ap_ready(w_mul_fu_79_ap_ready),
    .a(a),
    .b(c),
    .ap_return(w_mul_fu_79_ap_return)
);

mul x_mul_fu_87(
    .ap_ready(x_mul_fu_87_ap_ready),
    .a(a),
    .b(d),
    .ap_return(x_mul_fu_87_ap_return)
);

mul y_mul_fu_95(
    .ap_ready(y_mul_fu_95_ap_ready),
    .a(v_mul_fu_71_ap_return),
    .b(x_mul_fu_87_ap_return),
    .ap_return(y_mul_fu_95_ap_return)
);

assign add_ln36_1_fu_103_p2 = (w_mul_fu_79_ap_return + v_mul_fu_71_ap_return);

assign add_ln36_2_fu_109_p2 = (x_mul_fu_87_ap_return + y_mul_fu_95_ap_return);

assign f = (add_ln36_2_fu_109_p2 + add_ln36_1_fu_103_p2);

endmodule //inOutFunction
