-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inOutFunction is
port (
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    c : IN STD_LOGIC_VECTOR (31 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    f : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of inOutFunction is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "inOutFunction,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=35.472000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=4271,HLS_VERSION=2020_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal v_mul_fu_71_ap_ready : STD_LOGIC;
    signal v_mul_fu_71_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal w_mul_fu_79_ap_ready : STD_LOGIC;
    signal w_mul_fu_79_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal x_mul_fu_87_ap_ready : STD_LOGIC;
    signal x_mul_fu_87_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal y_mul_fu_95_ap_ready : STD_LOGIC;
    signal y_mul_fu_95_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_2_fu_109_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_1_fu_103_p2 : STD_LOGIC_VECTOR (31 downto 0);

    component mul IS
    port (
        ap_ready : OUT STD_LOGIC;
        a : IN STD_LOGIC_VECTOR (31 downto 0);
        b : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    v_mul_fu_71 : component mul
    port map (
        ap_ready => v_mul_fu_71_ap_ready,
        a => a,
        b => b,
        ap_return => v_mul_fu_71_ap_return);

    w_mul_fu_79 : component mul
    port map (
        ap_ready => w_mul_fu_79_ap_ready,
        a => a,
        b => c,
        ap_return => w_mul_fu_79_ap_return);

    x_mul_fu_87 : component mul
    port map (
        ap_ready => x_mul_fu_87_ap_ready,
        a => a,
        b => d,
        ap_return => x_mul_fu_87_ap_return);

    y_mul_fu_95 : component mul
    port map (
        ap_ready => y_mul_fu_95_ap_ready,
        a => v_mul_fu_71_ap_return,
        b => x_mul_fu_87_ap_return,
        ap_return => y_mul_fu_95_ap_return);




    add_ln36_1_fu_103_p2 <= std_logic_vector(unsigned(w_mul_fu_79_ap_return) + unsigned(v_mul_fu_71_ap_return));
    add_ln36_2_fu_109_p2 <= std_logic_vector(unsigned(x_mul_fu_87_ap_return) + unsigned(y_mul_fu_95_ap_return));
    f <= std_logic_vector(unsigned(add_ln36_2_fu_109_p2) + unsigned(add_ln36_1_fu_103_p2));
end behav;
