-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simple_combinational_circuit is
port (
    a : IN STD_LOGIC;
    b : IN STD_LOGIC;
    c : IN STD_LOGIC;
    d : OUT STD_LOGIC );
end;


architecture behav of simple_combinational_circuit is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "simple_combinational_circuit,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.978000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=6,HLS_VERSION=2020_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal and_ln11_fu_55_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln11_fu_55_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_61_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln11_fu_55_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_61_p2 : STD_LOGIC_VECTOR (0 downto 0);


begin



    and_ln11_fu_55_p0 <= (0=>a, others=>'-');
    and_ln11_fu_55_p1 <= (0=>b, others=>'-');
    and_ln11_fu_55_p2 <= (and_ln11_fu_55_p1 and and_ln11_fu_55_p0);
    d <= (xor_ln11_fu_61_p2(0) or and_ln11_fu_55_p2(0));
    xor_ln11_fu_61_p0 <= (0=>c, others=>'-');
    xor_ln11_fu_61_p2 <= (xor_ln11_fu_61_p0 xor ap_const_lv1_1);
end behav;
